In [1]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

# array([2, 3, 4])
print(a.dtype)

a = np.zeros((1, 2))
b = np.array([1.2, 3.5, 5.1])
print(b.dtype)

a = np.array([1, 2, 3, 4])


# c = np.array([1, 2], [3, 4], dtype=complex)
# print(c)

print(np.zeros((3, 4)))
print(np.ones((2, 3, 4), dtype=np.int16))
print(np.empty((2, 3)))
print(np.arange(10, 30, 5))
print(np.arange(0, 2, 0.3))
print(np.linspace(0, 2, 9))
print(a = np.arange(6))
print(np.arange(12).reshape(4, 3))
c = np.arange(24).reshape(2, 3, 4)
print(c)

np.arange(0, 2, 0.3) # 0.3은 step
a = np.linspace(0, 2, 9) # 9는 개수
print(a) 

a = np.arange(6)
print(a)

b = np.arange(12).reshape(4, 3)
print(b)

c = np.arange(24).reshape(2, 3, 4)
print(c)

x = np.arange(10)
print(x)

print(x[2], x[-2])

x.shape = (2, 5)

[[1 2 3]
 [4 5 6]]
int64
float64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


TypeError: 'a' is an invalid keyword argument for print()

In [2]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
x = np.arange(10)

print(x)
print()

x.shape = (2, 5)
print(x)

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a)
print()

print(a[[0, 1, 2, 0], [0, 2, 0, 1]])
#a[0, 0]
#a[1, 2]
#a[2, 0]
#a[0, 1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 6 7 2]


In [9]:
x = np.arange(10)
print(x)
print()

print(x[2:5]) # step <- 1 [2, 3, 4]
print()

print(x[:-7]) # start <- 0 [0, 1, 2]

[0 1 2 3 4 5 6 7 8 9]

[2 3 4]

[0 1 2]


In [16]:
y = np.arange(35).reshape(5, 7)
print(y) # 1D

print()

print(y[1: 5: 2, ::3]) # [1:5:2] -> 1, 3행 출력 [0: 끝까지: 3] -> 0, 3, 6

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]

[[ 7 10 13]
 [21 24 27]]


In [19]:
a = np.array(range(6)).reshape(2,3)
print(a)
print()

bool_idx = a > 2
print(bool_idx)

print()
print(a[bool_idx])

print(a[a > 2]) #a에서 특정 요소 뽑는데 2보다 큰 것들만 뽑아와라 a[bool_idx]와 같음

[[0 1 2]
 [3 4 5]]

[[False False False]
 [ True  True  True]]

[3 4 5]
[3 4 5]


In [22]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print()

b = np.copy(a[:2]) # 0, 1
print(b)
print()

b[0, 0] = -1
print(b)

print()
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[1 2 3 4]
 [5 6 7 8]]

[[-1  2  3  4]
 [ 5  6  7  8]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
import torch
torch.cuda.is_available()

False

In [31]:
a = np.floor(np.random.random((3, 4)))
print(a)
print()

print(a.ravel()) # returns the array, flattened
print()

print(a.reshape)
print()

a.resize((2, 6))
print(a)

a.reshape(3, -1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

<built-in method reshape of numpy.ndarray object at 0x7fd95bfeb090>

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
# 작성 코드
arr = np.zeros((5, 5))
for i in [0,4]:
    arr[i, :] = 1
    arr[:, i] = 1
print(arr)
print()

# 예시 코드 1
arr = np.ones((5, 5))
for i in [0, 4]:
    arr[i, :] = 0
    arr[:, i] = 0
print(arr)
print()

# 예시 코드 2
x = np.ones((3, 3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [85]:
# 작성 코드
arr = np.zeros((8, 8), dtype=intarr = np.zeros((8, 8), dtype=int드)

for i in range(8):
    for j in range(8):
        if (i+j) % 2 == 1:
            arr[i,j] = 1


print(arr)
print()

# 예시 코드
x = np.zeros((8, 8), dtype = int)

x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [87]:
cls = np.array([180, 72, 172, 66, 162, 60, 167, 53, 176, 80, 155, 60, 177, 77, 130, 40])
cls.resize(2, len(cls)//4, 2)
print(cls)

[[[180  72]
  [172  66]
  [162  60]
  [167  53]]

 [[176  80]
  [155  60]
  [177  77]
  [130  40]]]


In [ ]:
x = np.array([[1, 2],
             [3, 4]])
y = np.array([[5, 6],
              [7, 8]])

print(x + y)
print(x - y)